apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    native.cicd/version: {cicd-version}
    app.kubernetes.io/name: {app-name}
    app.kubernetes.io/component: {app-component}
    app.kubernetes.io/version: {app-version}
  name: {app-name}
  namespace: {namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {app-name}
      app.kubernetes.io/component: {app-component}
      app.kubernetes.io/version: {app-version}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {app-name}
        app.kubernetes.io/component: {app-component}
        app.kubernetes.io/version: {app-version}
    spec:
      initContainers:
      - name: "wireguard-init"
        image: "busybox"
        command: ["sh", "-c","sysctl -w net.ipv4.ip_forward=1"]
        securityContext:
          privileged: true
      containers:
      - name: {app-name}
        image: {image}
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
        env:
        - name: TZ
          value: {TZ}
        - name: SERVER_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: lockwire-keys
              key: server_private.key
        ports:
        - containerPort: 51820
          protocol: UDP
        resources:
          requests:
            memory: {memory-request}
            cpu: {cpu-request}
          limits:
            memory: {memory-limit}
            cpu: {cpu-limit}
        volumeMounts:
        - name: config
          mountPath: /config
        - name: host-volumes
          mountPath: /lib/modules
      volumes:
      - name: config
        configMap:
          name: wireguard-server-config
      - name: host-volumes
        hostPath:
          path: /lib/modules
          type: Directory