---
kind: Service
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: wireguard
  name: wireguard-svc
  namespace: wireguard
spec:
  type: NodePort
  ports:
  - port: 51820
    nodePort: 31820
    protocol: UDP
    targetPort: 51820
  selector:
    app.kubernetes.io/name: wireguard