apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: wireguard
  labels:
    app.kubernetes.io/name: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wireguard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wireguard
    spec:
      initContainers:
      - name: "wireguard-init"
        image: "busybox"
        command: ["sh", "-c","sysctl -w net.ipv4.ip_forward=1"]
        securityContext:
          privileged: true
      containers:
      - name: wireguard
        image: docker.io/linuxserver/wireguard:1.0.20210914
        envFrom:
        - configMapRef:
            name: wireguard-configmap 
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
          # privileged: true
        volumeMounts:
          - name: wg-config
            mountPath: /config
          - name: host-volumes
            mountPath: /lib/modules
        ports:
        - containerPort: 51820
          protocol: UDP
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
        - name: wg-config
          persistentVolumeClaim:
            claimName: pvc-wireguard 
        - name: host-volumes
          hostPath:
            path: /lib/modules
            type: Directory