apiVersion: v1
kind: Namespace
metadata:
  name: {app-name}
  labels:
    native.cicd/version: {cicd-version}
    app.kubernetes.io/name: {app-name}
    app.kubernetes.io/component: {app-component}
    app.kubernetes.io/version: {app-version}
